name: Update README.md

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      
      - name: Install python dependencies
        run: pip3 install requests bs4

      - name: Update README.md
        run: python3 get_last_posts.py

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated latest blog posts
